[[commentaries]]
ajmc_id = "cu31924087948174"
zotero_id = "3PSZEAK5"

[[commentaries]]
ajmc_id = "Finglass2011"
zotero_id = "YDZHMDY8"

[[commentaries]]
ajmc_id = "Hermann1851"
zotero_id = "JPALGCFZ"

[[commentaries]]
ajmc_id = "sophoclesplaysa05campgoog"
zotero_id = "YZ347EC5"

[[commentaries]]
ajmc_id = "bsb10234118"
zotero_id = "JTP6DUJI"

[[commentaries]]
ajmc_id = "lestragdiesdeso00tourgoog"
zotero_id = "QNJZHKEP"

[[commentaries]]
ajmc_id = "Untersteiner1934"
zotero_id = "NYSQ2SDV"

[[commentaries]]
ajmc_id = "Wecklein1894"
zotero_id = "SGQ3ESQS"

[[commentaries]]
ajmc_id = "Colonna1975"
zotero_id = ""

[[commentaries]]
ajmc_id = "DeRomilly1976"
zotero_id = "IP7NDYE5"

[[commentaries]]
ajmc_id = "Ferrari1974"
zotero_id = "W2X3M5CD"

[[commentaries]]
ajmc_id = "Garvie1998"
zotero_id = "3SKERGNH"

[[commentaries]]
ajmc_id = "Kamerbeek1953"
zotero_id = "PJBEUQZ3"

[[commentaries]]
ajmc_id = "Paduano1982"
zotero_id = "KLP4VLTH"

[[commentaries]]
ajmc_id = "SchneidewinNauckRadermacher1913"
zotero_id = "K2HAGNCQ"

[[commentaries]]
ajmc_id = "Stanford1963"
zotero_id = "J8LIE7AR"

[[commentaries]]
ajmc_id = "sophokle1v3soph"
zotero_id = "Z3E52E63"